baseURL = "https://cybersecurity.kr"
languageCode ="ko-kr"
title = "Cybersecurity.kr"
paginate = 5
copyright = "CYBERSECURITY.KR ALL RIGHTS RESERVED"
pygmentsCodeFences = "true"

[params]
author_email = "loon@cybersecurity.kr"
author_github = "dglee2"

[[menu.main]]
name="Home"
identifier="Home"
url="/"
weight=1

[[menu.main]]
identifier="Philosophy"
name="Mission / Vision / Core Values"
url="/philosophy/"
weight=2

[[menu.main]]
identifier="Services"
name="ICT Infrastructure / Security / Software / Training"
url="/services/"
weight=3

[[menu.main]]
identifier="Portfolio"
name="Examples and Samples"
url="/portfolio/"
weight=4

[[menu.main]]
identifier="Blog"
name="News and Articles"
url="/blog/"
weight=5
