baseURL = "http://cybersecurity.kr/"
languageCode = "en-us"
title = "Cybersecurity.kr"
paginate = 5
copyright = "CYBERSECURITY.KR ALL RIGHTS RESERVED"
pygmentsCodeFences = "true"

[params]
author_email = "loon@cybersecurity.kr"
author_github = "dglee2"

[[menu.main]]
name="Home"
identifier="Home"
url="/"
weight=1

[[menu.main]]
name="Opensource *NIX"
identifier="freebsd / openbsd"
url="/freebsd/"
weight=2

[[menu.main]]
name="Gimp Toolkit"
identifier="gtk"
url="/gtk/"
weight=3

[[menu.main]]
name="Information Security Management System"
identifier="isms"
url="/isms/"
weight=4

[[menu.main]]
name="Penetration Test"
identifier="pentest"
description="description"
url="/pentest/"
weight=5
