baseURL = "/"
languageCode = "en-us"
title = "Cybersecurity.kr"
paginate = 5
copyright = "CYBERSECURITY.KR ALL RIGHTS RESERVED"
[params]
author_email = "loon@cybersecurity.kr"
author_github = "dglee2"

[[menu.main]]
name="Home"
identifier="Home"
url="/"
weight=1

[[menu.main]]
name="FreeBSD Name"
identifier="freebsd"
url="/freebsd/"
weight=2

[[menu.main]]
name="GTK Name"
identifier="gtk"
url="/gtk/"
weight=3

[[menu.main]]
name="ISMS Name"
identifier="isms"
url="/isms/"
weight=4

[[menu.main]]
name="Pen Test Name"
identifier="pentest"
description="description"
url="/pentest/"
weight=5
